export const primary= "#26168bc1"
export const secondary= "#82ccee5a"
export const cardBgColor= "linear-gradient(90deg, #afe6ffbe 50%, #facd7ba9)"
export const cardForeColor= "violet"
export const titleColor= "black"